"""empty message

Revision ID: 9fbaccee7c91
Revises: bbb6eae59947
Create Date: 2020-08-17 09:26:24.047190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fbaccee7c91'
down_revision = 'bbb6eae59947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('n_followings', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('n_follwers', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('n_friends', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'n_friends')
    op.drop_column('users', 'n_follwers')
    op.drop_column('users', 'n_followings')
    # ### end Alembic commands ###
