"""empty message

Revision ID: bbb6eae59947
Revises: 11d65b51ea1d
Create Date: 2020-08-15 21:51:23.925183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb6eae59947'
down_revision = '11d65b51ea1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_relationships',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['users.id_'], ),
    sa.ForeignKeyConstraint(['right_id'], ['users.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('friend_relationships',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['users.id_'], ),
    sa.ForeignKeyConstraint(['right_id'], ['users.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.add_column('users', sa.Column('gender', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=11), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'gender')
    op.drop_table('friend_relationships')
    op.drop_table('follow_relationships')
    # ### end Alembic commands ###
