"""empty message

Revision ID: d49898f44b1c
Revises: e7ba4904d90f
Create Date: 2020-08-17 09:45:07.702329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49898f44b1c'
down_revision = 'e7ba4904d90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('n_posts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'n_posts')
    # ### end Alembic commands ###
